# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy multiple JAR apps to Azure Web Apps

on:
  push:
    branches:
      - master
      - integratingServices
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - user-service
          - mission-service
          - configuration-service
          - orchestrator-service
          - authentication-service

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build with Maven
        run: |
          cd ${{ matrix.service }}
          mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.service }}
          path: '${{ github.workspace }}/${{ matrix.service }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        service:
          - user-service
          - mission-service
          - configuration-service
          - orchestrator-service
          - authentication-service

    environment:
      name: 'Production-${{ matrix.service }}'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.service }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_15B6BF247E9045B4B5708C7C1636B1E7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C03C0BA721D54960AC2527C32F2E52B9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CCEBAEBE0C8D4B92AB1E4EB3AE964409 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: '${{ matrix.service }}-app'
          slot-name: 'Production'
          package: '*.jar'
          
